.gitignore, config/settings.py, notices/models.py
=> [#4] notices 앱 models.py 생성

accounts/models.py, config/settings.py, requirements.txt
=> [#7] accounts models.py 생성

config/urls.py, products/models.py
models.py 오타 수정
users는 아직 안바꿈
close #8
=> [#5] models.py 수정

notices/models.py, requirements/models.py
requirements 앱 models.py 완성. +(notices앱 models.py 살짝 수정)
#6
=> [#6] requirements 앱 models.py 완성. +(notices앱 models.py 살짝 수정)

accounts/models.py
accounts models.py에 request 테이블 추가
=> [#9] accounts models.py에 request 테이블 추가

config/urls.py, facilities/models.py, facilities/urls.py, facilities/views.py, products/models.py
=> [#5] models.py user 수정

config/settings.py
settings.py MIDDLEWARE 수정
close #24
=> [#11] settings.py MIDDLEWARE 수정

accounts/models.py, requirements/models.py
requirements app에 models.py(전공과목, 교양과목, 외국어 시험 기준점수 속성 수정)
=> [#12]requirements app에 models.py(전공과목, 교양과목, 외국어 시험 기준점수 속성 수정)

requirements/models.py
requirements models.py ExtraForeignTest - descreption 수정
=> [#12] requirements models.py ExtraForeignTest - descreption 수정

requirements/models.py
=> [#9] requirements models.py 수정

requirements/models.py
보내주신 파일들에 맞춰서 DB 스키마 수정 후 적재 -> models.py 수정했습니다.
이번에 변경사항들 잘 보시면서 맞는지 확인 부탁드립니다.
특히 교양필수예외 테이블이 많이 변동되었으니 확인 부탁드립니다.
close #32
=> [#13] requirements models.py 수정

notices/models.py, notices/views.py
=> [#14]notices 앱 models.py 수정

accounts/views.py
=> [#17] 구글 소셜 로그인 view UPDATE

config/settings.py, notices/serializers.py, notices/urls.py, notices/views.py
=> [#18] notices view 수정+

facilities/serializers.py
response에 facility_desc 추가
close #48
=> [#8] main page 응답 response 수정

accounts/views.py
=> [#20] 백엔드 배포 주소로 변경

facilities/views.py
notice_filter 오타 수정,,ㅜㅠ 죄송합니다.
close #54
=> [#21] views.py 오타 수정

accounts/views.py
=> [#22] google_callback UPDATE

accounts/views.py
=> [#22] google_callback 수정

facilities/views.py
이중전공 이수 학점 반환 로직 수정했습니다
close. #59
=> [#23] main view 졸업 이수 학점 계산 로직 수정

accounts/urls.py
=> [#24] access 토큰 재발급

notices/serializers.py, notices/urls.py, notices/views.py
=> [#25] notices view 졸업요건 수정페이지 추가

accounts/urls.py, accounts/views.py
=> [#26] AgreeMentAPIView 기능 구현

accounts/views.py
=> [#29] 로그인 연동

config/settings.py, config/urls.py, requirements/serializers.py, requirements/urls.py, requirements/views.py
=> [#31] CollegeListAPIView 기능 구현

requirements/serializers.py, requirements/urls.py, requirements/views.py
=> [#32] 학과 및 교양 과목 구분 정보 api 기능 구현

notices/urls.py, notices/views.py
=> [#37] 전공만 보기버튼 api 기능 구현

requirements/serializers.py, requirements/urls.py, requirements/views.py
=> [#36] IRequirementsAPIView 기능 구현

requirements/serializers.py, requirements/urls.py, requirements/views.py
=> [#38] 졸업요건 그래프 api 기능 구현

notices/urls.py, notices/views.py
=> [#40] 마이페이지 수정 api

requirements/urls.py, requirements/views.py
=> [#41] 졸업요건 필수과목 api 구현

facilities/views.py
=> [#43] main view 수정

facilities/views.py
=> [#44] main 수정

accounts/views.py
=> [#48] 로그인 response 변경

facilities/views.py
=> [#47] main api 수정

requirements/views.py
=> [#50] 그래프 api 수정

requirements/views.py
데이터사이언스 전공의 경우를 고려해야 함
서로 다른 두 전공이 같은 과목을 필수 과목으로 정했으며 유저가 그 두 전공을 동시에 본전공과 이중전공으로 삼았을 경우, 둘 다 인정해줘야 함 
교양과목 이수 완료 처리 함수 분리시켰습니다
close. #116
=> [#52] RequirementSubjectAPIView 수정

facilities/views.py
유저 id로 바로 조회하게 만들었음
close. #118
=> [#53] main 공지사항 수정
